# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnaEkran_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(859, 608)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Original = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Original.setGeometry(QtCore.QRect(120, 130, 281, 61))
        self.pushButton_Original.setObjectName("pushButton_Original")
        self.label_baslik = QtWidgets.QLabel(self.centralwidget)
        self.label_baslik.setGeometry(QtCore.QRect(260, 20, 286, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_baslik.setFont(font)
        self.label_baslik.setObjectName("label_baslik")
        self.pushButton_Gurultulu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Gurultulu.setGeometry(QtCore.QRect(470, 130, 281, 61))
        self.pushButton_Gurultulu.setObjectName("pushButton_Gurultulu")
        self.pushButton_Normalize = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Normalize.setGeometry(QtCore.QRect(130, 290, 271, 61))
        self.pushButton_Normalize.setObjectName("pushButton_Normalize")
        self.labeloriginal = QtWidgets.QLabel(self.centralwidget)
        self.labeloriginal.setGeometry(QtCore.QRect(80, 90, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeloriginal.setFont(font)
        self.labeloriginal.setObjectName("labeloriginal")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 80, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 230, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 240, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_Dengesizlik = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Dengesizlik.setGeometry(QtCore.QRect(500, 290, 261, 61))
        self.pushButton_Dengesizlik.setObjectName("pushButton_Dengesizlik")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(370, 390, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 859, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ana Ekran"))
        self.pushButton_Original.setText(_translate("MainWindow", "Orijinal Veti Seti Çalışması"))
        self.label_baslik.setText(_translate("MainWindow", "Makine Öğrenmesi Projesi"))
        self.pushButton_Gurultulu.setText(_translate("MainWindow", "Gürültülü Veri Seti Çalışması"))
        self.pushButton_Normalize.setText(_translate("MainWindow", "Normalize Edilmiş Veri Seti Çalışması"))
        self.labeloriginal.setText(_translate("MainWindow", "Deney1- Orijinal Veri Seti"))
        self.label.setText(_translate("MainWindow", "Deney2-Gürültülü Veri Seti"))
        self.label_2.setText(_translate("MainWindow", "Deney3-Normalize Edilmiş Veri Seti"))
        self.label_3.setText(_translate("MainWindow", "Deney4-Dengesiz Veri Seti"))
        self.pushButton_Dengesizlik.setText(_translate("MainWindow", "Dengesiz Veri Setiyle Çalış"))
