# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dengesizlik_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(705, 696)
        self.label_baslik = QtWidgets.QLabel(Form2)
        self.label_baslik.setGeometry(QtCore.QRect(220, 40, 286, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_baslik.setFont(font)
        self.label_baslik.setObjectName("label_baslik")
        self.radioButton_knn = QtWidgets.QRadioButton(Form2)
        self.radioButton_knn.setGeometry(QtCore.QRect(90, 230, 151, 31))
        self.radioButton_knn.setObjectName("radioButton_knn")
        self.radioButton_dt = QtWidgets.QRadioButton(Form2)
        self.radioButton_dt.setGeometry(QtCore.QRect(90, 310, 161, 31))
        self.radioButton_dt.setObjectName("radioButton_dt")
        self.radioButton_lr = QtWidgets.QRadioButton(Form2)
        self.radioButton_lr.setGeometry(QtCore.QRect(90, 270, 171, 31))
        self.radioButton_lr.setObjectName("radioButton_lr")
        self.pushButton_veriSetiYkle = QtWidgets.QPushButton(Form2)
        self.pushButton_veriSetiYkle.setGeometry(QtCore.QRect(50, 110, 251, 28))
        self.pushButton_veriSetiYkle.setObjectName("pushButton_veriSetiYkle")
        self.pushButton_veriSetiGster = QtWidgets.QPushButton(Form2)
        self.pushButton_veriSetiGster.setGeometry(QtCore.QRect(50, 160, 251, 31))
        self.pushButton_veriSetiGster.setObjectName("pushButton_veriSetiGster")
        self.pushButton_onslemeHazrlk = QtWidgets.QPushButton(Form2)
        self.pushButton_onslemeHazrlk.setGeometry(QtCore.QRect(380, 110, 251, 81))
        self.pushButton_onslemeHazrlk.setObjectName("pushButton_onslemeHazrlk")
        self.pushButton_predict_proba = QtWidgets.QPushButton(Form2)
        self.pushButton_predict_proba.setGeometry(QtCore.QRect(160, 410, 371, 71))
        self.pushButton_predict_proba.setObjectName("pushButton_predict_proba")
        self.pushButton_veriSetiniEgit = QtWidgets.QPushButton(Form2)
        self.pushButton_veriSetiniEgit.setGeometry(QtCore.QRect(60, 350, 251, 28))
        self.pushButton_veriSetiniEgit.setObjectName("pushButton_veriSetiniEgit")
        self.pushButton_DengesizligiGider = QtWidgets.QPushButton(Form2)
        self.pushButton_DengesizligiGider.setGeometry(QtCore.QRect(460, 300, 161, 41))
        self.pushButton_DengesizligiGider.setObjectName("pushButton_DengesizligiGider")
        self.comboBox_DengesizlikYntemleri = QtWidgets.QComboBox(Form2)
        self.comboBox_DengesizlikYntemleri.setGeometry(QtCore.QRect(410, 250, 211, 31))
        self.comboBox_DengesizlikYntemleri.setObjectName("comboBox_DengesizlikYntemleri")
        self.comboBox_DengesizlikYntemleri.addItem("")
        self.comboBox_DengesizlikYntemleri.addItem("")
        self.pushButtonMetrikler = QtWidgets.QPushButton(Form2)
        self.pushButtonMetrikler.setGeometry(QtCore.QRect(160, 490, 371, 61))
        self.pushButtonMetrikler.setObjectName("pushButtonMetrikler")
        self.pushButtonDengesizligiGster = QtWidgets.QPushButton(Form2)
        self.pushButtonDengesizligiGster.setGeometry(QtCore.QRect(400, 200, 221, 41))
        self.pushButtonDengesizligiGster.setObjectName("pushButtonDengesizligiGster")
        self.pushButtonDengesizligiGster_2 = QtWidgets.QPushButton(Form2)
        self.pushButtonDengesizligiGster_2.setGeometry(QtCore.QRect(400, 350, 221, 41))
        self.pushButtonDengesizligiGster_2.setObjectName("pushButtonDengesizligiGster_2")
        self.pushButtonModelOrnek = QtWidgets.QPushButton(Form2)
        self.pushButtonModelOrnek.setGeometry(QtCore.QRect(160, 570, 371, 61))
        self.pushButtonModelOrnek.setObjectName("pushButtonModelOrnek")

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "Dengesizlik"))
        self.label_baslik.setText(_translate("Form2", "Makine Öğrenmesi Projesi"))
        self.radioButton_knn.setText(_translate("Form2", "KNN Modeli"))
        self.radioButton_dt.setText(_translate("Form2", "Decision Tree"))
        self.radioButton_lr.setText(_translate("Form2", "Lojistik Regresyon"))
        self.pushButton_veriSetiYkle.setText(_translate("Form2", "Veri Setini Yükle"))
        self.pushButton_veriSetiGster.setText(_translate("Form2", "Veri Setini Göster"))
        self.pushButton_onslemeHazrlk.setText(_translate("Form2", "Sayısal Olmayan Sütunları Kategorize Et"))
        self.pushButton_predict_proba.setText(_translate("Form2", "En İyi Modelde Predict_proba ve Predict Metorları"))
        self.pushButton_veriSetiniEgit.setText(_translate("Form2", "Veri Setini Eğit"))
        self.pushButton_DengesizligiGider.setText(_translate("Form2", "Dengesizliği Gider"))
        self.comboBox_DengesizlikYntemleri.setItemText(0, _translate("Form2", "ROS (Random OverSampling)"))
        self.comboBox_DengesizlikYntemleri.setItemText(1, _translate("Form2", "RUS (Random UnderSampling)"))
        self.pushButtonMetrikler.setText(_translate("Form2", "Doğruluk Metriklerini ve Karmaşıklık Matrisini Göster"))
        self.pushButtonDengesizligiGster.setText(_translate("Form2", "Dengesziliği Göster"))
        self.pushButtonDengesizligiGster_2.setText(_translate("Form2", "Son durumu göster"))
        self.pushButtonModelOrnek.setText(_translate("Form2", "Modelin Uygulanma Örneği"))
