# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gürültülü_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form4(object):
    def setupUi(self, Form4):
        Form4.setObjectName("Form4")
        Form4.resize(695, 823)
        self.radioButton_dt = QtWidgets.QRadioButton(Form4)
        self.radioButton_dt.setGeometry(QtCore.QRect(280, 460, 161, 31))
        self.radioButton_dt.setObjectName("radioButton_dt")
        self.pushButton_veriSetiniEgit = QtWidgets.QPushButton(Form4)
        self.pushButton_veriSetiniEgit.setGeometry(QtCore.QRect(250, 500, 251, 28))
        self.pushButton_veriSetiniEgit.setObjectName("pushButton_veriSetiniEgit")
        self.label_baslik = QtWidgets.QLabel(Form4)
        self.label_baslik.setGeometry(QtCore.QRect(220, 40, 286, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_baslik.setFont(font)
        self.label_baslik.setObjectName("label_baslik")
        self.pushButton_veriSetiGster = QtWidgets.QPushButton(Form4)
        self.pushButton_veriSetiGster.setGeometry(QtCore.QRect(50, 160, 251, 31))
        self.pushButton_veriSetiGster.setObjectName("pushButton_veriSetiGster")
        self.pushButton_onslemeHazrlk = QtWidgets.QPushButton(Form4)
        self.pushButton_onslemeHazrlk.setGeometry(QtCore.QRect(380, 110, 251, 81))
        self.pushButton_onslemeHazrlk.setObjectName("pushButton_onslemeHazrlk")
        self.pushButton_EksikVerileriDoldur = QtWidgets.QPushButton(Form4)
        self.pushButton_EksikVerileriDoldur.setGeometry(QtCore.QRect(290, 300, 161, 41))
        self.pushButton_EksikVerileriDoldur.setObjectName("pushButton_EksikVerileriDoldur")
        self.radioButton_lr = QtWidgets.QRadioButton(Form4)
        self.radioButton_lr.setGeometry(QtCore.QRect(280, 420, 171, 31))
        self.radioButton_lr.setObjectName("radioButton_lr")
        self.pushButton_predict_proba = QtWidgets.QPushButton(Form4)
        self.pushButton_predict_proba.setGeometry(QtCore.QRect(180, 540, 371, 71))
        self.pushButton_predict_proba.setObjectName("pushButton_predict_proba")
        self.comboBox_EksikVerilerDoldur = QtWidgets.QComboBox(Form4)
        self.comboBox_EksikVerilerDoldur.setGeometry(QtCore.QRect(240, 260, 211, 31))
        self.comboBox_EksikVerilerDoldur.setObjectName("comboBox_EksikVerilerDoldur")
        self.comboBox_EksikVerilerDoldur.addItem("")
        self.comboBox_EksikVerilerDoldur.addItem("")
        self.comboBox_EksikVerilerDoldur.addItem("")
        self.comboBox_EksikVerilerDoldur.addItem("")
        self.pushButton_veriSetiYkle = QtWidgets.QPushButton(Form4)
        self.pushButton_veriSetiYkle.setGeometry(QtCore.QRect(50, 110, 251, 28))
        self.pushButton_veriSetiYkle.setObjectName("pushButton_veriSetiYkle")
        self.radioButton_knn = QtWidgets.QRadioButton(Form4)
        self.radioButton_knn.setGeometry(QtCore.QRect(280, 380, 151, 31))
        self.radioButton_knn.setObjectName("radioButton_knn")
        self.label = QtWidgets.QLabel(Form4)
        self.label.setGeometry(QtCore.QRect(200, 210, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtonMetrikler = QtWidgets.QPushButton(Form4)
        self.pushButtonMetrikler.setGeometry(QtCore.QRect(180, 640, 371, 61))
        self.pushButtonMetrikler.setObjectName("pushButtonMetrikler")
        self.pushButtonModelOrnek = QtWidgets.QPushButton(Form4)
        self.pushButtonModelOrnek.setGeometry(QtCore.QRect(180, 720, 371, 61))
        self.pushButtonModelOrnek.setObjectName("pushButtonModelOrnek")

        self.retranslateUi(Form4)
        QtCore.QMetaObject.connectSlotsByName(Form4)

    def retranslateUi(self, Form4):
        _translate = QtCore.QCoreApplication.translate
        Form4.setWindowTitle(_translate("Form4", "Gürültülü"))
        self.radioButton_dt.setText(_translate("Form4", "Decision Tree"))
        self.pushButton_veriSetiniEgit.setText(_translate("Form4", "Veri Setini Eğit"))
        self.label_baslik.setText(_translate("Form4", "Makine Öğrenmesi Projesi"))
        self.pushButton_veriSetiGster.setText(_translate("Form4", "Veri Setini Göster"))
        self.pushButton_onslemeHazrlk.setText(_translate("Form4", "Sayısal Olmayan Sütunları Kategorize Et"))
        self.pushButton_EksikVerileriDoldur.setText(_translate("Form4", "Eksik Verileri Doldur"))
        self.radioButton_lr.setText(_translate("Form4", "Lojistik Regresyon"))
        self.pushButton_predict_proba.setText(_translate("Form4", "En İyi Modelde Predict_proba ve Predict Metorları"))
        self.comboBox_EksikVerilerDoldur.setItemText(0, _translate("Form4", "En çok tekrar eden değer ile"))
        self.comboBox_EksikVerilerDoldur.setItemText(1, _translate("Form4", "Ortalamayla"))
        self.comboBox_EksikVerilerDoldur.setItemText(2, _translate("Form4", "Ortanca ile"))
        self.comboBox_EksikVerilerDoldur.setItemText(3, _translate("Form4", "Sıfır(0) ile"))
        self.pushButton_veriSetiYkle.setText(_translate("Form4", "Veri Setini Yükle"))
        self.radioButton_knn.setText(_translate("Form4", "KNN Modeli"))
        self.label.setText(_translate("Form4", "Gürültüyü Gider"))
        self.pushButtonMetrikler.setText(_translate("Form4", "Doğruluk Metriklerini ve Karmaşıklık Matrisini Göster"))
        self.pushButtonModelOrnek.setText(_translate("Form4", "Modelin Uygulanma Örneği"))
