# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Normalizasyon_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Normalizasyon(object):
    def setupUi(self, Normalizasyon):
        Normalizasyon.setObjectName("Normalizasyon")
        Normalizasyon.resize(721, 751)
        self.pushButton_veriSetiYkle = QtWidgets.QPushButton(Normalizasyon)
        self.pushButton_veriSetiYkle.setGeometry(QtCore.QRect(50, 110, 251, 28))
        self.pushButton_veriSetiYkle.setObjectName("pushButton_veriSetiYkle")
        self.radioButton_dt = QtWidgets.QRadioButton(Normalizasyon)
        self.radioButton_dt.setGeometry(QtCore.QRect(110, 300, 161, 31))
        self.radioButton_dt.setObjectName("radioButton_dt")
        self.radioButton_lr = QtWidgets.QRadioButton(Normalizasyon)
        self.radioButton_lr.setGeometry(QtCore.QRect(110, 260, 171, 31))
        self.radioButton_lr.setObjectName("radioButton_lr")
        self.pushButton_predict_proba = QtWidgets.QPushButton(Normalizasyon)
        self.pushButton_predict_proba.setGeometry(QtCore.QRect(190, 410, 371, 71))
        self.pushButton_predict_proba.setObjectName("pushButton_predict_proba")
        self.pushButton_veriSetiniEgit = QtWidgets.QPushButton(Normalizasyon)
        self.pushButton_veriSetiniEgit.setGeometry(QtCore.QRect(80, 340, 251, 28))
        self.pushButton_veriSetiniEgit.setObjectName("pushButton_veriSetiniEgit")
        self.pushButton_veriSetiGster = QtWidgets.QPushButton(Normalizasyon)
        self.pushButton_veriSetiGster.setGeometry(QtCore.QRect(50, 160, 251, 31))
        self.pushButton_veriSetiGster.setObjectName("pushButton_veriSetiGster")
        self.label_baslik = QtWidgets.QLabel(Normalizasyon)
        self.label_baslik.setGeometry(QtCore.QRect(220, 40, 286, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_baslik.setFont(font)
        self.label_baslik.setObjectName("label_baslik")
        self.radioButton_knn = QtWidgets.QRadioButton(Normalizasyon)
        self.radioButton_knn.setGeometry(QtCore.QRect(110, 220, 151, 31))
        self.radioButton_knn.setObjectName("radioButton_knn")
        self.pushButton_onslemeHazrlk = QtWidgets.QPushButton(Normalizasyon)
        self.pushButton_onslemeHazrlk.setGeometry(QtCore.QRect(380, 110, 251, 81))
        self.pushButton_onslemeHazrlk.setObjectName("pushButton_onslemeHazrlk")
        self.pushButtonMetrikler = QtWidgets.QPushButton(Normalizasyon)
        self.pushButtonMetrikler.setGeometry(QtCore.QRect(190, 500, 371, 61))
        self.pushButtonMetrikler.setObjectName("pushButtonMetrikler")
        self.pushButtonNormalizeEt = QtWidgets.QPushButton(Normalizasyon)
        self.pushButtonNormalizeEt.setGeometry(QtCore.QRect(400, 210, 231, 51))
        self.pushButtonNormalizeEt.setObjectName("pushButtonNormalizeEt")
        self.pushButtonModelOrnek = QtWidgets.QPushButton(Normalizasyon)
        self.pushButtonModelOrnek.setGeometry(QtCore.QRect(190, 580, 371, 61))
        self.pushButtonModelOrnek.setObjectName("pushButtonModelOrnek")
        self.pushButtonNormalizeEt_2 = QtWidgets.QPushButton(Normalizasyon)
        self.pushButtonNormalizeEt_2.setGeometry(QtCore.QRect(400, 280, 231, 51))
        self.pushButtonNormalizeEt_2.setObjectName("pushButtonNormalizeEt_2")

        self.retranslateUi(Normalizasyon)
        QtCore.QMetaObject.connectSlotsByName(Normalizasyon)

    def retranslateUi(self, Normalizasyon):
        _translate = QtCore.QCoreApplication.translate
        Normalizasyon.setWindowTitle(_translate("Normalizasyon", "Normalizasyon"))
        self.pushButton_veriSetiYkle.setText(_translate("Normalizasyon", "Veri Setini Yükle"))
        self.radioButton_dt.setText(_translate("Normalizasyon", "Decision Tree"))
        self.radioButton_lr.setText(_translate("Normalizasyon", "Lojistik Regresyon"))
        self.pushButton_predict_proba.setText(_translate("Normalizasyon", "En İyi Modelde Predict_proba ve Predict Metorları"))
        self.pushButton_veriSetiniEgit.setText(_translate("Normalizasyon", "Veri Setini Eğit"))
        self.pushButton_veriSetiGster.setText(_translate("Normalizasyon", "Veri Setini Göster"))
        self.label_baslik.setText(_translate("Normalizasyon", "Makine Öğrenmesi Projesi"))
        self.radioButton_knn.setText(_translate("Normalizasyon", "KNN Modeli"))
        self.pushButton_onslemeHazrlk.setText(_translate("Normalizasyon", "Sayısal Olmayan Sütunları Kategorize Et"))
        self.pushButtonMetrikler.setText(_translate("Normalizasyon", "Doğruluk Metriklerini ve Karmaşıklık Matrisini Göster"))
        self.pushButtonNormalizeEt.setText(_translate("Normalizasyon", "Min-max ile normalize et "))
        self.pushButtonModelOrnek.setText(_translate("Normalizasyon", "Modelin Uygulanma Örneği"))
        self.pushButtonNormalizeEt_2.setText(_translate("Normalizasyon", "Z-skoru ile normalize et"))
