# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Orijinal_Veri_Seti_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(729, 779)
        self.pushButton_veriSetiGster = QtWidgets.QPushButton(Form)
        self.pushButton_veriSetiGster.setGeometry(QtCore.QRect(70, 150, 251, 31))
        self.pushButton_veriSetiGster.setObjectName("pushButton_veriSetiGster")
        self.pushButton_onslemeHazrlk = QtWidgets.QPushButton(Form)
        self.pushButton_onslemeHazrlk.setGeometry(QtCore.QRect(400, 100, 251, 81))
        self.pushButton_onslemeHazrlk.setObjectName("pushButton_onslemeHazrlk")
        self.radioButton_knn = QtWidgets.QRadioButton(Form)
        self.radioButton_knn.setGeometry(QtCore.QRect(310, 200, 151, 31))
        self.radioButton_knn.setObjectName("radioButton_knn")
        self.pushButton_kfold = QtWidgets.QPushButton(Form)
        self.pushButton_kfold.setGeometry(QtCore.QRect(200, 480, 371, 61))
        self.pushButton_kfold.setObjectName("pushButton_kfold")
        self.label_baslik = QtWidgets.QLabel(Form)
        self.label_baslik.setGeometry(QtCore.QRect(230, 40, 286, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_baslik.setFont(font)
        self.label_baslik.setObjectName("label_baslik")
        self.pushButton_veriSetiYkle = QtWidgets.QPushButton(Form)
        self.pushButton_veriSetiYkle.setGeometry(QtCore.QRect(70, 100, 251, 28))
        self.pushButton_veriSetiYkle.setObjectName("pushButton_veriSetiYkle")
        self.pushButton_predict_proba = QtWidgets.QPushButton(Form)
        self.pushButton_predict_proba.setGeometry(QtCore.QRect(200, 390, 371, 71))
        self.pushButton_predict_proba.setObjectName("pushButton_predict_proba")
        self.pushButton_veriSetiniEgit = QtWidgets.QPushButton(Form)
        self.pushButton_veriSetiniEgit.setGeometry(QtCore.QRect(280, 320, 251, 28))
        self.pushButton_veriSetiniEgit.setObjectName("pushButton_veriSetiniEgit")
        self.radioButton_dt = QtWidgets.QRadioButton(Form)
        self.radioButton_dt.setGeometry(QtCore.QRect(310, 280, 161, 31))
        self.radioButton_dt.setObjectName("radioButton_dt")
        self.radioButton_lr = QtWidgets.QRadioButton(Form)
        self.radioButton_lr.setGeometry(QtCore.QRect(310, 240, 171, 31))
        self.radioButton_lr.setObjectName("radioButton_lr")
        self.pushButtonMetrikler = QtWidgets.QPushButton(Form)
        self.pushButtonMetrikler.setGeometry(QtCore.QRect(200, 570, 371, 61))
        self.pushButtonMetrikler.setObjectName("pushButtonMetrikler")
        self.pushButtonModelOrnek = QtWidgets.QPushButton(Form)
        self.pushButtonModelOrnek.setGeometry(QtCore.QRect(200, 660, 371, 61))
        self.pushButtonModelOrnek.setObjectName("pushButtonModelOrnek")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_veriSetiGster.setText(_translate("Form", "Veri Setini Göster"))
        self.pushButton_onslemeHazrlk.setText(_translate("Form", "Sayısal Olmayan Sütunları Kategorize Et"))
        self.radioButton_knn.setText(_translate("Form", "KNN Modeli"))
        self.pushButton_kfold.setText(_translate("Form", "K-Fold Uygula"))
        self.label_baslik.setText(_translate("Form", "Makine Öğrenmesi Projesi"))
        self.pushButton_veriSetiYkle.setText(_translate("Form", "Veri Setini Yükle"))
        self.pushButton_predict_proba.setText(_translate("Form", "En İyi Modelde Predict_proba ve Predict Metorları"))
        self.pushButton_veriSetiniEgit.setText(_translate("Form", "Veri Setini Eğit"))
        self.radioButton_dt.setText(_translate("Form", "Decision Tree"))
        self.radioButton_lr.setText(_translate("Form", "Lojistik Regresyon"))
        self.pushButtonMetrikler.setText(_translate("Form", "Doğruluk Metriklerini ve Karmaşıklık Matrisini Göster"))
        self.pushButtonModelOrnek.setText(_translate("Form", "Modelin Uygulanma Örneği"))
